// variables
var timerId = $('#currentDay');


// Setting the date with momentjs
var dateTime = moment();
timerId.text(dateTime.format("dddd, MMMM Do Y"))


// CREATE THE TIME BLOCKS FOR BUSINESS HOURS BETWEEN 9AM to 5PM COLOR CODED- GREY= EVENT HAPPENED, PINK= CURRENT HOUR, GREEN= UPCOMING. USE BOOTSTRAP TO CREATE IT

// INFO IS STORED IN LOCAL FILE AND IT COMES BACK UP ON THE SCREEN ONCE ITS REFRESHED


// JQUERY AND THE SAVE BUTON IS PAIRED TO THE SIBLING OF THE INFO/TEXT BLOCK OF TIME